version: '3'
services:
  app:
    build: .
    ports:
      - "3000:3000"
    environment:
      POSTGRES_PRISMA_URL: postgresql://postgres:postgres@db:5432/postgres
      POSTGRES_URL_NON_POOLING: postgresql://postgres:postgres@db:5432/postgres?connection_limit=1
    depends_on:
      - db
